title: IATI Decipher
description: Browser plugins for deciphering IATI organisation files.
show_downloads: false
theme: jekyll-theme-slate
github:
  owner_name: Publish What You Fund
  owner_url: http://www.publishwhatyoufund.org
